version: '3.7'

secrets:
  apitokens:
    file: ./db_apitokens.txt
services:
  caas-database:
    hostname: "caas-database"
    image: postgres:13.1
    environment:
      API_DB_USER: ${API_DB_USER}
      API_DB_PASS: ${API_DB_PASS}
      API_DB_DATABASE: ${API_DB_DATABASE}
      APP_DB_TOKENS: ${APP_DB_TOKENS}
      POSTGRES_PASSWORD: ${API_DB_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
    secrets:
      - apitokens
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - ${DB_PORT}:${DB_PORT}

